services:
  app:
    # For local testing email posting network_mode is set to host
    # See push-emails.sh
    network_mode: host
    image: container-cwvjxo
    build:
      context: ./src
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./src/web
        target: /usr/src/app
